apiVersion: v1
kind: ConfigMap
metadata:
  name: bookitnow-config
data:
  postgres_host: postgres-svc
  postgres_port: "5432"
  postgres_dbname: appdb
---
apiVersion: v1
kind: Secret
metadata:
  name: bookitnow-secrets
type: Opaque
data:
  postgres_username: cG9zdGdyZXM=
  postgres_password: cG9zdGdyZXM=