apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: kafka-kraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:latest
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: kafka-svc:9092
            - name: CONNECT_GROUP_ID
              value: kafkaGroup
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: kafka-connect-configs
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: kafka-connect-offsets
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: kafka-connect-status
            - name: SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.storage.StringConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: localhost
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  namespace: kafka-kraft
spec:
  selector:
    app: kafka-connect
  ports:
    - protocol: TCP
      port: 8083
  type: ClusterIP
