#spring:
#  application:
#    name: temporary-reservation-service
#  kafka:
#    producer:
#      bootstrap-servers: kafka-svc:9092
#    consumer:
#      bootstrap-servers: kafka-svc:9092
#      group-id: bookItNow
#    streams:
#      properties:
#        spring.json.trusted.packages: "*"
#        state-dir: /tmp/kafka-streams/
#  config:
#    activate:
#      on-profile: k8s
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:appdb}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}
server:
  port: 8081

spring:
  application:
    name: temp-reservation
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafkaGroup
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC
    username: user
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true